let plusBtn1 = document.querySelector('.plusfaq1')
let crossBtn1 = document.querySelector('.crossfaq1')
let plusBtn2 = document.querySelector('.plusfaq2')
let crossBtn2 = document.querySelector('.crossfaq2')
let plusBtn3 = document.querySelector('.plusfaq3')
let crossBtn3 = document.querySelector('.crossfaq3')
let plusBtn4 = document.querySelector('.plusfaq4')
let crossBtn4 = document.querySelector('.crossfaq4')
let plusBtn5 = document.querySelector('.plusfaq5')
let crossBtn5 = document.querySelector('.crossfaq5')
let plusBtn6 = document.querySelector('.plusfaq6')
let crossBtn6 = document.querySelector('.crossfaq6')
let data1 = document.querySelector('.ques1')
let data2 = document.querySelector('.ques2')
let data3 = document.querySelector('.ques3')
let data4 = document.querySelector('.ques4')
let data5 = document.querySelector('.ques5')
let data6 = document.querySelector('.ques6')

plusBtn1.addEventListener('click',() => {
    plusBtn1.classList.add('hidden')
    plusBtn1.classList.remove('inline')
    data1.classList.remove('hidden')
    data1.classList.add('inline')
    crossBtn1.classList.remove('hidden')
    crossBtn1.classList.add('inline')
})
crossBtn1.addEventListener('click',() => {
    plusBtn1.classList.remove('hidden')
    plusBtn1.classList.add('inline')
    data1.classList.remove('inline')
    data1.classList.add('hidden')
    crossBtn1.classList.remove('inline')
    crossBtn1.classList.add('hidden')
})
plusBtn2.addEventListener('click',() => {
    plusBtn2.classList.add('hidden')
    plusBtn2.classList.remove('inline')
    data2.classList.remove('hidden')
    data2.classList.add('inline')
    crossBtn2.classList.remove('hidden')
    crossBtn2.classList.add('inline')
})
crossBtn2.addEventListener('click',() => {
    plusBtn2.classList.remove('hidden')
    plusBtn2.classList.add('inline')
    data2.classList.remove('inline')
    data2.classList.add('hidden')
    crossBtn2.classList.remove('inline')
    crossBtn2.classList.add('hidden')
})
plusBtn3.addEventListener('click',() => {
    plusBtn3.classList.add('hidden')
    plusBtn3.classList.remove('inline')
    data3.classList.remove('hidden')
    data3.classList.add('inline')
    crossBtn3.classList.remove('hidden')
    crossBtn3.classList.add('inline')
})
crossBtn3.addEventListener('click',() => {
    plusBtn3.classList.remove('hidden')
    plusBtn3.classList.add('inline')
    data3.classList.remove('inline')
    data3.classList.add('hidden')
    crossBtn3.classList.remove('inline')
    crossBtn3.classList.add('hidden')
})
plusBtn4.addEventListener('click',() => {
    plusBtn4.classList.add('hidden')
    plusBtn4.classList.remove('inline')
    data4.classList.remove('hidden')
    data4.classList.add('inline')
    crossBtn4.classList.remove('hidden')
    crossBtn4.classList.add('inline')
})
crossBtn4.addEventListener('click',() => {
    plusBtn4.classList.remove('hidden')
    plusBtn4.classList.add('inline')
    data4.classList.remove('inline')
    data4.classList.add('hidden')
    crossBtn4.classList.remove('inline')
    crossBtn4.classList.add('hidden')
})
plusBtn5.addEventListener('click',() => {
    plusBtn5.classList.add('hidden')
    plusBtn5.classList.remove('inline')
    data5.classList.remove('hidden')
    data5.classList.add('inline')
    crossBtn5.classList.remove('hidden')
    crossBtn5.classList.add('inline')
})
crossBtn5.addEventListener('click',() => {
    plusBtn5.classList.remove('hidden')
    plusBtn5.classList.add('inline')
    data5.classList.remove('inline')
    data5.classList.add('hidden')
    crossBtn5.classList.remove('inline')
    crossBtn5.classList.add('hidden')
})
plusBtn6.addEventListener('click',() => {
    plusBtn6.classList.add('hidden')
    plusBtn6.classList.remove('inline')
    data6.classList.remove('hidden')
    data6.classList.add('inline')
    crossBtn6.classList.remove('hidden')
    crossBtn6.classList.add('inline')
})
crossBtn6.addEventListener('click',() => {
    plusBtn6.classList.remove('hidden')
    plusBtn6.classList.add('inline')
    data6.classList.remove('inline')
    data6.classList.add('hidden')
    crossBtn6.classList.remove('inline')
    crossBtn6.classList.add('hidden')
})